import eslint from '@eslint/js';
import prettier from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';
import vueEslintParser from 'vue-eslint-parser';

export default [
  {
    ignores: [
      'node_modules/',
      'dist/',
      'public/',
      '*.md',
      '*.json',
      '.eslintignore',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 12,
      sourceType: 'module',
      globals: {
        browser: true,
        node: true,
        es2021: true,
        window: true,
        document: true,
        localStorage: true,
        WebSocket: true,
        FileReader: true,
        Blob: true,
        setInterval: true,
        clearInterval: true,
        setTimeout: true,
        clearTimeout: true,
        SpeechSynthesisUtterance: true,
        location: true,
        fetch: true,
        console: true,
        isNaN: true,
        require: true,
        module: true,
        process: true,
        __dirname: true,
        btoa: true,
      },
    },
    plugins: {
      prettier,
    },
    rules: {
      ...eslint.configs.recommended.rules,
      ...prettierConfig.rules,
      'prettier/prettier': 'error',
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-unused-vars': 'warn',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
    },
  },
  {
    files: ['**/*.vue'],
    languageOptions: {
      ecmaVersion: 12,
      sourceType: 'module',
      parser: vueEslintParser,
      parserOptions: {
        ecmaVersion: 12,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        browser: true,
        node: true,
        es2021: true,
        window: true,
        document: true,
        localStorage: true,
        WebSocket: true,
        FileReader: true,
        Blob: true,
        setInterval: true,
        clearInterval: true,
        setTimeout: true,
        clearTimeout: true,
        SpeechSynthesisUtterance: true,
        location: true,
        fetch: true,
        console: true,
        isNaN: true,
        alert: true,
      },
    },
    plugins: {
      prettier,
    },
    rules: {
      ...eslint.configs.recommended.rules,
      ...prettierConfig.rules,
      'prettier/prettier': 'error',
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-unused-vars': 'warn',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
    },
  },
  {
    files: ['cypress/**/*.js'],
    languageOptions: {
      ecmaVersion: 12,
      sourceType: 'module',
      globals: {
        cy: true,
        Cypress: true,
        describe: true,
        it: true,
        beforeEach: true,
        afterEach: true,
        btoa: true,
      },
    },
    plugins: {
      prettier,
    },
    rules: {
      ...eslint.configs.recommended.rules,
      ...prettierConfig.rules,
      'prettier/prettier': 'error',
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-unused-vars': 'warn',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
    },
  },
];
